version: '3'

services:
  frontend:
    image: myfrontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend/src:/usr/share/nginx/html"
    ports:
      - 80:80
  backend:
    image: mybackend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - "./backend/src:/app"
    ports:
      - 5000:5000

